import type { ToolRecord } from '@/types';

export const aiTools: ToolRecord[] = [
  {
    id: 'text-summary',
    name: '文本摘要',
    description: '使用本地算法提取文本关键句子生成摘要',
    category: 'ai',
    icon: 'SparklesIcon',
    version: '1.0.0',
    source: 'builtin',
    permissions: [],
    inputSchema: [
      { key: 'text', label: '文本内容', type: 'textarea', placeholder: '输入需要摘要的文本...', required: true },
      {
        key: 'length',
        label: '摘要长度',
        type: 'select',
        defaultValue: 'medium',
        options: [
          { label: '简短', value: 'short' },
          { label: '中等', value: 'medium' },
          { label: '详细', value: 'long' },
        ],
      },
    ],
    outputFormat: 'text',
  },
  {
    id: 'text-translate',
    name: '文本翻译',
    description: '文本翻译（即将上线，敬请期待）',
    category: 'ai',
    icon: 'LanguagesIcon',
    version: '1.0.0',
    source: 'builtin',
    permissions: [],
    inputSchema: [
      { key: 'text', label: '文本内容', type: 'textarea', placeholder: '输入需要翻译的文本...', required: true },
      {
        key: 'sourceLang',
        label: '源语言',
        type: 'select',
        defaultValue: 'zh',
        options: [
          { label: '中文', value: 'zh' },
          { label: '英语', value: 'en' },
          { label: '日语', value: 'ja' },
          { label: '韩语', value: 'ko' },
        ],
      },
      {
        key: 'targetLang',
        label: '目标语言',
        type: 'select',
        defaultValue: 'en',
        options: [
          { label: '中文', value: 'zh' },
          { label: '英语', value: 'en' },
          { label: '日语', value: 'ja' },
          { label: '韩语', value: 'ko' },
        ],
      },
    ],
    outputFormat: 'text',
  },
  {
    id: 'speech-to-text',
    name: '语音转文字',
    description: '通过浏览器语音识别将语音转为文字',
    icon: 'MicIcon',
    category: 'ai',
    version: '1.0.0',
    source: 'builtin' as const,
    permissions: ['microphone'],
    inputSchema: [
      { key: 'language', label: '识别语言', type: 'select', options: [{ label: '中文(普通话)', value: 'zh-CN' }, { label: '英文', value: 'en-US' }, { label: '日文', value: 'ja-JP' }, { label: '韩文', value: 'ko-KR' }], defaultValue: 'zh-CN' },
      { key: 'continuous', label: '连续识别', type: 'checkbox', defaultValue: true },
    ],
    outputFormat: 'text',
  },
  {
    id: 'text-to-speech',
    name: '文字转语音',
    description: '将文字转为语音朗读',
    icon: 'Volume2Icon',
    category: 'ai',
    version: '1.0.0',
    source: 'builtin' as const,
    permissions: [],
    inputSchema: [
      { key: 'text', label: '文本内容', type: 'textarea', placeholder: '输入要朗读的文字...', required: true },
      { key: 'rate', label: '语速', type: 'select', options: [{ label: '慢速', value: '0.7' }, { label: '正常', value: '1' }, { label: '快速', value: '1.3' }, { label: '极快', value: '1.6' }], defaultValue: '1' },
      { key: 'voice', label: '声音', type: 'select', options: [{ label: '默认', value: 'default' }], defaultValue: 'default' },
    ],
    outputFormat: 'text',
  },
  {
    id: 'e-signature',
    name: '电子签名',
    description: '在画板上手写签名，生成透明背景签名图片',
    icon: 'PenLineIcon',
    category: 'ai',
    version: '1.0.0',
    source: 'builtin' as const,
    permissions: [],
    inputSchema: [
      { key: 'signerName', label: '签名者姓名', type: 'text', placeholder: '输入姓名...', required: true },
      { key: 'color', label: '笔迹颜色', type: 'color', defaultValue: '#000000' },
      { key: 'fontStyle', label: '字体风格', type: 'select', options: [{ label: '手写体', value: 'cursive' }, { label: '楷体', value: 'serif' }, { label: '艺术体', value: 'fantasy' }], defaultValue: 'cursive' },
    ],
    outputFormat: 'blob',
  },
];
