import type { ToolRecord } from '@/types';

export const funTools: ToolRecord[] = [
  {
    id: 'what-to-eat',
    name: '今天吃什么',
    description: '选择菜系，随机推荐美食帮你解决吃饭难题',
    category: 'fun',
    icon: 'UtensilsCrossedIcon',
    version: '1.0.0',
    source: 'builtin',
    permissions: [],
    inputSchema: [
      {
        key: 'cuisine',
        label: '菜系',
        type: 'select',
        defaultValue: 'all',
        options: [
          { label: '随便看看', value: 'all' },
          { label: '中式', value: 'chinese' },
          { label: '西式', value: 'western' },
          { label: '日韩', value: 'japanese' },
        ],
      },
      { key: 'count', label: '推荐数量', type: 'number', defaultValue: 3 },
    ],
    outputFormat: 'text',
    tips: '帮你解决吃饭选择困难症，每次随机推荐',
  },
  {
    id: 'fancy-text-generator',
    name: '装饰文字生成',
    description: '将普通文字转换为粗体、斜体、花体等艺术效果',
    category: 'fun',
    icon: 'TypeOutlineIcon',
    version: '1.0.0',
    source: 'builtin',
    permissions: [],
    inputSchema: [
      {
        key: 'text',
        label: '输入文字',
        type: 'text',
        required: true,
        placeholder: '输入要转换的文字',
      },
      {
        key: 'style',
        label: '文字风格',
        type: 'select',
        defaultValue: 'bold',
        options: [
          { label: '粗体', value: 'bold' },
          { label: '斜体', value: 'italic' },
          { label: '花体', value: 'fancy' },
        ],
      },
    ],
    outputFormat: 'text',
    tips: '复制转换结果到微信、微博等平台即可使用',
  },
  {
    id: 'special-symbols',
    name: '特殊符号大全',
    description: '收集了表情、手势、箭头、货币等各种常用特殊符号，一键复制',
    category: 'fun',
    icon: 'SmilePlusIcon',
    version: '1.0.0',
    source: 'builtin',
    permissions: [],
    inputSchema: [
      {
        key: 'mode',
        label: '符号类型',
        type: 'select',
        defaultValue: 'emoji',
        options: [
          { label: '表情符号', value: 'emoji' },
          { label: '箭头数学', value: 'arrows' },
        ],
      },
    ],
    outputFormat: 'text',
    tips: '点击喜欢的符号即可复制到剪贴板',
  },
  {
    id: 'kinship-calculator',
    name: '亲戚称呼计算器',
    description: '输入关系描述（如爸爸的哥哥），自动计算亲戚称呼',
    category: 'fun',
    icon: 'UsersIcon',
    version: '1.0.0',
    source: 'builtin',
    permissions: [],
    inputSchema: [
      {
        key: 'relation',
        label: '关系描述',
        type: 'text',
        required: true,
        placeholder: '例如：爸爸的哥哥',
      },
    ],
    outputFormat: 'text',
    tips: '春节拜年必备，再也不怕叫错人了',
  },
  {
    id: 'idiom-chain',
    name: '成语接龙',
    description: '输入成语自动接下一个，并列出可接的备选',
    category: 'fun',
    icon: 'MessageCircleIcon',
    version: '1.0.0',
    source: 'builtin',
    permissions: [],
    inputSchema: [
      {
        key: 'word',
        label: '输入成语',
        type: 'text',
        required: true,
        placeholder: '例如：一心一意',
      },
    ],
    outputFormat: 'text',
    tips: '输入一个成语，帮你接下一个，可多次执行接长龙',
  },
  {
    id: 'meme-text-generator',
    name: '表情包文字生成',
    description: '选择风格生成表情包标题文字模板',
    category: 'fun',
    icon: 'ImagePlayIcon',
    version: '1.0.0',
    source: 'builtin',
    permissions: [],
    inputSchema: [
      { key: 'topText', label: '上方文字', type: 'text', placeholder: '如上句' },
      { key: 'bottomText', label: '下方文字', type: 'text', placeholder: '如下句' },
      {
        key: 'style',
        label: '风格',
        type: 'select',
        defaultValue: 'impact',
        options: [
          { label: 'IMPACT字体', value: 'impact' },
          { label: '甜蜜恋爱', value: 'heart' },
          { label: '暴怒吐槽', value: 'rage' },
          { label: '无奈心酸', value: 'sad' },
          { label: '快乐沙雕', value: 'happy' },
        ],
      },
    ],
    outputFormat: 'text',
    tips: '生成文案模板，可在表情包制作工具中使用',
  },
];