import type { ToolRecord } from '@/types';

export const funTools: ToolRecord[] = [
  {
    id: 'what-to-eat',
    name: '今天吃什么',
    description: '选择菜系，随机推荐美食帮你解决吃饭难题',
    category: 'fun',
    icon: 'UtensilsCrossedIcon',
    version: '1.0.0',
    source: 'builtin',
    permissions: [],
    inputSchema: [
      {
        key: 'cuisine',
        label: '菜系',
        type: 'select',
        defaultValue: 'all',
        options: [
          { label: '随便看看', value: 'all' },
          { label: '中式', value: 'chinese' },
          { label: '西式', value: 'western' },
          { label: '日韩', value: 'japanese' },
        ],
      },
      { key: 'count', label: '推荐数量', type: 'number', defaultValue: 3 },
    ],
    outputFormat: 'text',
    tips: '帮你解决吃饭选择困难症，每次随机推荐',
  },
  {
    id: 'fancy-text-generator',
    name: '装饰文字生成',
    description: '将普通文字转换为气泡圈、方形框、翻转等6种艺术字体效果',
    category: 'fun',
    icon: 'TypeOutlineIcon',
    version: '1.0.0',
    source: 'builtin',
    permissions: [],
    inputSchema: [
      {
        key: 'text',
        label: '输入文字',
        type: 'text',
        required: true,
        placeholder: '输入要转换的文字',
      },
      {
        key: 'style',
        label: '文字风格',
        type: 'select',
        defaultValue: 'bubbles',
        options: [
          { label: '气泡圈ⓔ', value: 'bubbles' },
          { label: '方形框🄰', value: 'squares' },
          { label: '混乱体z̾a̾l̾g̾o̾', value: 'zalgo' },
          { label: '删除线̶', value: 'strikethrough' },
          { label: '翻转文', value: 'flip' },
          { label: '数学粗体', value: 'bold' },
        ],
      },
    ],
    outputFormat: 'text',
    tips: '6种独特风格，每种产生完全不同的视觉输出',
  },
  {
    id: 'special-symbols',
    name: '特殊符号大全',
    description: '收集了表情、手势、箭头、货币等各种常用特殊符号，一键复制',
    category: 'fun',
    icon: 'SmilePlusIcon',
    version: '1.0.0',
    source: 'builtin',
    permissions: [],
    inputSchema: [
      {
        key: 'mode',
        label: '符号类型',
        type: 'select',
        defaultValue: 'emoji',
        options: [
          { label: '表情符号', value: 'emoji' },
          { label: '箭头数学', value: 'arrows' },
        ],
      },
    ],
    outputFormat: 'text',
    tips: '点击喜欢的符号即可复制到剪贴板',
  },
  {
    id: 'kinship-calculator',
    name: '亲戚称呼计算器',
    description: '输入关系描述（如爸爸的哥哥），自动计算亲戚称呼',
    category: 'fun',
    icon: 'UsersIcon',
    version: '1.0.0',
    source: 'builtin',
    permissions: [],
    inputSchema: [
      { key: 'path', label: '关系路径', type: 'text', placeholder: '如: 爸爸的哥哥 (或点击下方按钮组合)', defaultValue: '' },
    ],
    outputFormat: 'text',
    tips: '点击亲属按钮自动组合关系路径，如: 爸爸 + 的 + 哥哥 → 伯伯',
  },
  {
    id: 'idiom-chain',
    name: '成语接龙',
    description: '输入成语自动接下一个，支持难度选择和接力计数',
    category: 'fun',
    icon: 'MessageCircleIcon',
    version: '1.0.0',
    source: 'builtin',
    permissions: [],
    inputSchema: [
      { key: 'start', label: '输入成语', type: 'text', required: true, placeholder: '例如：一心一意' },
      { key: 'difficulty', label: '难度', type: 'select', defaultValue: 'normal', options: [{ label: '简单(含短成语)', value: 'easy' }, { label: '普通', value: 'normal' }, { label: '困难(仅四字)', value: 'hard' }] },
    ],
    outputFormat: 'text',
    tips: '输入开头成语，AI自动接龙，显示难度和轮次',
  },
  {
    id: 'meme-text-generator',
    name: '表情包文字生成',
    description: '给表情包添加文字 - 生成带描边的趣味文字图片',
    category: 'fun',
    icon: 'ImagePlayIcon',
    version: '1.0.0',
    source: 'builtin',
    permissions: [],
    inputSchema: [
      { key: 'text', label: '输入文字', type: 'text', placeholder: '输入要显示的文字...', defaultValue: '', required: true },
      {
        key: 'style',
        label: '风格',
        type: 'select',
        defaultValue: 'impact',
        options: [
          { label: '经典表情包(白字黑边)', value: 'impact' },
          { label: '卡通meme', value: 'meme' },
          { label: '复古终端绿屏', value: 'retro' },
          { label: '可爱粉色', value: 'cute' },
          { label: '戏剧夸张红字', value: 'dramatic' },
        ],
      },
    ],
    outputFormat: 'blob',
    tips: '选择风格点击执行，生成带描边特效的文字图片，可下载后贴到表情包上',
  },
];