import type { ToolRecord } from '@/types';

export const imageTools: ToolRecord[] = [
  {
    id: 'image-compress',
    name: '图片压缩',
    description: '使用Canvas API压缩图片，支持调整压缩质量和输出格式',
    category: 'image',
    icon: 'FileImageIcon',
    version: '1.0.0',
    source: 'builtin',
    permissions: [],
    inputSchema: [
      { key: 'file', label: '选择图片', type: 'file', accept: 'image/*', required: true },
      { key: 'quality', label: '压缩质量', type: 'number', defaultValue: 0.7, placeholder: '0.1-1.0' },
      {
        key: 'format',
        label: '输出格式',
        type: 'select',
        defaultValue: 'image/jpeg',
        options: [
          { label: 'JPEG', value: 'image/jpeg' },
          { label: 'PNG', value: 'image/png' },
          { label: 'WebP', value: 'image/webp' },
        ],
      },
    ],
    outputFormat: 'blob',
  },
  {
    id: 'image-convert',
    name: '格式转换',
    description: '在PNG、JPEG、WebP格式之间转换图片',
    category: 'image',
    icon: 'RefreshCwIcon',
    version: '1.0.0',
    source: 'builtin',
    permissions: [],
    inputSchema: [
      { key: 'file', label: '选择图片', type: 'file', accept: 'image/*', required: true },
      {
        key: 'targetFormat',
        label: '目标格式',
        type: 'select',
        defaultValue: 'image/webp',
        options: [
          { label: 'PNG', value: 'image/png' },
          { label: 'JPEG', value: 'image/jpeg' },
          { label: 'WebP', value: 'image/webp' },
        ],
      },
    ],
    outputFormat: 'blob',
  },
  {
    id: 'image-resize',
    name: '图片缩放',
    description: '调整图片尺寸，支持自定义宽高和保持宽高比',
    category: 'image',
    icon: 'MaximizeIcon',
    version: '1.0.0',
    source: 'builtin',
    permissions: [],
    inputSchema: [
      { key: 'file', label: '选择图片', type: 'file', accept: 'image/*', required: true },
      { key: 'width', label: '宽度', type: 'number', placeholder: '目标宽度(px)' },
      { key: 'height', label: '高度', type: 'number', placeholder: '目标高度(px)' },
      { key: 'keepRatio', label: '保持宽高比', type: 'checkbox', defaultValue: true },
    ],
    outputFormat: 'blob',
  },
  {
    id: 'id-photo',
    name: '证件照制作',
    description: '制作标准证件照，支持更换背景色和裁剪尺寸',
    category: 'image',
    icon: 'UserIcon',
    version: '1.0.0',
    source: 'builtin',
    permissions: [],
    inputSchema: [
      { key: 'file', label: '选择图片', type: 'file', accept: 'image/*', required: true },
      {
        key: 'bgColor',
        label: '背景颜色',
        type: 'select',
        defaultValue: 'blue',
        options: [
          { label: '蓝色', value: 'blue' },
          { label: '红色', value: 'red' },
          { label: '白色', value: 'white' },
        ],
      },
      {
        key: 'size',
        label: '证件照尺寸',
        type: 'select',
        defaultValue: '1inch',
        options: [
          { label: '1寸(25x35mm)', value: '1inch' },
          { label: '2寸(35x49mm)', value: '2inch' },
          { label: '小1寸(22x32mm)', value: 'small1inch' },
        ],
      },
    ],
    outputFormat: 'blob',
  },
  {
    id: 'image-watermark',
    name: '图片加水印',
    description: '为图片添加文字水印，支持自定义位置和样式',
    category: 'image',
    icon: 'StampIcon',
    version: '1.0.0',
    source: 'builtin',
    permissions: [],
    inputSchema: [
      { key: 'file', label: '选择图片', type: 'file', accept: 'image/*', required: true },
      { key: 'text', label: '水印文字', type: 'text', placeholder: '输入水印文字...', required: true },
      {
        key: 'position',
        label: '水印位置',
        type: 'select',
        defaultValue: 'bottom-right',
        options: [
          { label: '左上角', value: 'top-left' },
          { label: '右上角', value: 'top-right' },
          { label: '居中', value: 'center' },
          { label: '左下角', value: 'bottom-left' },
          { label: '右下角', value: 'bottom-right' },
          { label: '平铺', value: 'tile' },
        ],
      },
      { key: 'opacity', label: '透明度', type: 'number', defaultValue: 0.3, placeholder: '0-1透明度' },
      { key: 'color', label: '水印颜色', type: 'color', defaultValue: '#ffffff' },
    ],
    outputFormat: 'blob',
  },
  {
    id: 'image-watermark-remove',
    name: '图片去水印',
    description: '通过区域修复方式去除图片上的水印',
    category: 'image',
    icon: 'EraserIcon',
    version: '1.0.0',
    source: 'builtin',
    permissions: [],
    inputSchema: [
      { key: 'file', label: '选择图片', type: 'file', accept: 'image/*', required: true },
      {
        key: 'mode',
        label: '去除模式',
        type: 'select',
        defaultValue: 'auto-light',
        options: [
          { label: '自动检测(浅色水印)', value: 'auto-light' },
          { label: '自动检测(深色水印)', value: 'auto-dark' },
          { label: '边缘区域清除', value: 'edge-clean' },
        ],
      },
      { key: 'strength', label: '去除强度', type: 'number', defaultValue: 5, placeholder: '1-10强度' },
    ],
    outputFormat: 'blob',
  },
  {
    id: 'image-stitch',
    name: '长图拼接',
    description: '将多张图片纵向或横向拼接为长图',
    category: 'image',
    icon: 'RowsIcon',
    version: '1.0.0',
    source: 'builtin',
    permissions: [],
    inputSchema: [
      { key: 'files', label: '选择图片(可多选)', type: 'file', accept: 'image/*', required: true, multiple: true },
      {
        key: 'direction',
        label: '拼接方向',
        type: 'select',
        defaultValue: 'vertical',
        options: [
          { label: '纵向拼接', value: 'vertical' },
          { label: '横向拼接', value: 'horizontal' },
        ],
      },
      { key: 'gap', label: '图片间距', type: 'number', defaultValue: 0, placeholder: '图片间距(px)' },
    ],
    outputFormat: 'blob',
  },
  {
    id: 'image-ocr',
    name: '图片提取文字',
    description: '从图片中识别和提取文字内容(OCR)',
    category: 'image',
    icon: 'ScanTextIcon',
    version: '1.0.0',
    source: 'builtin',
    permissions: [],
    inputSchema: [
      { key: 'file', label: '选择图片', type: 'file', accept: 'image/*', required: true },
      {
        key: 'lang',
        label: '识别语言',
        type: 'select',
        defaultValue: 'chi_sim+eng',
        options: [
          { label: '中文', value: 'chi_sim' },
          { label: '英文', value: 'eng' },
          { label: '中英混合', value: 'chi_sim+eng' },
        ],
      },
    ],
    outputFormat: 'json',
  },
  {
    id: 'image-to-pdf',
    name: '图片转PDF',
    description: '将图片转换为PDF文件，支持多张图片合并',
    icon: 'FileDownIcon',
    category: 'image',
    version: '1.0.0',
    source: 'builtin' as const,
    permissions: [],
    inputSchema: [
      { key: 'files', label: '选择图片(可多选)', type: 'file', accept: 'image/*', required: true, multiple: true },
      { key: 'orientation', label: '页面方向', type: 'select', options: [{ label: '自动', value: 'auto' }, { label: '纵向', value: 'portrait' }, { label: '横向', value: 'landscape' }], defaultValue: 'auto' },
      { key: 'pageSize', label: '页面大小', type: 'select', options: [{ label: 'A4', value: 'a4' }, { label: 'Letter', value: 'letter' }], defaultValue: 'a4' },
    ],
    outputFormat: 'blob',
  },
  {
    id: 'screenshot-annotate',
    name: '截图标注',
    description: '在图片上添加标注、箭头、文字和框选',
    icon: 'PenToolIcon',
    category: 'image',
    version: '1.0.0',
    source: 'builtin' as const,
    permissions: [],
    inputSchema: [
      { key: 'file', label: '选择图片', type: 'file', accept: 'image/*', required: true },
      { key: 'annotationType', label: '标注类型', type: 'select', options: [{ label: '红色箭头', value: 'arrow-red' }, { label: '绿色箭头', value: 'arrow-green' }, { label: '红色框选', value: 'rect-red' }, { label: '绿色框选', value: 'rect-green' }, { label: '文字标注', value: 'text' }], defaultValue: 'arrow-red' },
      { key: 'startX', label: '起始X(%)', type: 'number', defaultValue: 20, placeholder: '0-100' },
      { key: 'startY', label: '起始Y(%)', type: 'number', defaultValue: 30, placeholder: '0-100' },
      { key: 'endX', label: '结束X(%)', type: 'number', defaultValue: 70, placeholder: '0-100' },
      { key: 'endY', label: '结束Y(%)', type: 'number', defaultValue: 60, placeholder: '0-100' },
      { key: 'text', label: '标注文字', type: 'text', placeholder: '输入标注文字...', defaultValue: '' },
    ],
    outputFormat: 'blob',
  },
];
