import type { ToolRecord } from '@/types';

export const lifeTools: ToolRecord[] = [
  {
    id: 'qrcode-generator',
    name: '二维码生成',
    description: '将文本或链接生成二维码图片',
    category: 'everyday',
    icon: 'QrCodeIcon',
    version: '1.0.0',
    source: 'builtin',
    permissions: [],
    inputSchema: [
      { key: 'content', label: '内容', type: 'text', placeholder: '输入文本或链接...', required: true },
      {
        key: 'size',
        label: '尺寸',
        type: 'select',
        defaultValue: '256',
        options: [
          { label: '128x128', value: '128' },
          { label: '256x256', value: '256' },
          { label: '512x512', value: '512' },
        ],
      },
      { key: 'color', label: '前景色', type: 'color', defaultValue: '#000000' },
    ],
    outputFormat: 'image',
    tips: '输入文本或网址即可生成可扫描的二维码',
  },
  {
    id: 'unit-converter',
    name: '单位转换',
    description: '在长度、重量、温度等单位之间转换',
    category: 'everyday',
    icon: 'RulerIcon',
    version: '1.0.0',
    source: 'builtin',
    permissions: [],
    inputSchema: [
      { key: 'value', label: '数值', type: 'number', placeholder: '输入数值...', required: true },
      {
        key: 'category',
        label: '类别',
        type: 'select',
        defaultValue: 'length',
        options: [
          { label: '长度', value: 'length' },
          { label: '重量', value: 'weight' },
          { label: '温度', value: 'temperature' },
        ],
      },
      {
        key: 'fromUnit',
        label: '源单位',
        type: 'select',
        defaultValue: 'm',
        options: [
          { label: '米 (m)', value: 'm' },
          { label: '千米 (km)', value: 'km' },
          { label: '厘米 (cm)', value: 'cm' },
          { label: '英寸 (in)', value: 'in' },
          { label: '英尺 (ft)', value: 'ft' },
          { label: '英里 (mi)', value: 'mi' },
          { label: '千克 (kg)', value: 'kg' },
          { label: '克 (g)', value: 'g' },
          { label: '磅 (lb)', value: 'lb' },
          { label: '盎司 (oz)', value: 'oz' },
          { label: '摄氏度 (°C)', value: 'c' },
          { label: '华氏度 (°F)', value: 'f' },
          { label: '开尔文 (K)', value: 'k' },
        ],
      },
      {
        key: 'toUnit',
        label: '目标单位',
        type: 'select',
        defaultValue: 'km',
        options: [
          { label: '米 (m)', value: 'm' },
          { label: '千米 (km)', value: 'km' },
          { label: '厘米 (cm)', value: 'cm' },
          { label: '英寸 (in)', value: 'in' },
          { label: '英尺 (ft)', value: 'ft' },
          { label: '英里 (mi)', value: 'mi' },
          { label: '千克 (kg)', value: 'kg' },
          { label: '克 (g)', value: 'g' },
          { label: '磅 (lb)', value: 'lb' },
          { label: '盎司 (oz)', value: 'oz' },
          { label: '摄氏度 (°C)', value: 'c' },
          { label: '华氏度 (°F)', value: 'f' },
          { label: '开尔文 (K)', value: 'k' },
        ],
      },
    ],
    outputFormat: 'text',
    tips: '支持长度、重量、温度等多种单位互转',
  },
  {
    id: 'mortgage-calculator',
    name: '房贷计算器',
    description: '计算房贷月供、总利息和还款计划',
    category: 'everyday',
    icon: 'HomeIcon',
    version: '1.0.0',
    source: 'builtin',
    permissions: [],
    inputSchema: [
      { key: 'principal', label: '贷款金额', type: 'number', placeholder: '贷款金额(万元)', required: true, defaultValue: 100 },
      { key: 'rate', label: '年利率', type: 'number', placeholder: '年利率(%)', required: true, defaultValue: 3.5 },
      { key: 'years', label: '贷款年限', type: 'number', placeholder: '贷款年限', required: true, defaultValue: 30 },
      {
        key: 'method',
        label: '还款方式',
        type: 'select',
        defaultValue: 'equal-payment',
        options: [
          { label: '等额本息', value: 'equal-payment' },
          { label: '等额本金', value: 'equal-principal' },
        ],
      },
    ],
    outputFormat: 'text',
    tips: '支持等额本息和等额本金两种还款方式',
  },
  {
    id: 'tax-calculator',
    name: '个税计算器',
    description: '计算个人所得税和到手工资',
    category: 'everyday',
    icon: 'ReceiptIcon',
    version: '1.0.0',
    source: 'builtin',
    permissions: [],
    inputSchema: [
      { key: 'salary', label: '税前月薪', type: 'number', placeholder: '税前月薪(元)', required: true, defaultValue: 15000 },
      { key: 'socialInsurance', label: '五险一金', type: 'number', placeholder: '五险一金(元)', defaultValue: 2000 },
      { key: 'threshold', label: '起征点', type: 'number', placeholder: '起征点(元)', defaultValue: 5000 },
      { key: 'deductions', label: '专项附加扣除', type: 'number', placeholder: '专项附加扣除(元)', defaultValue: 0 },
    ],
    outputFormat: 'text',
    tips: '输入税前月薪即可快速计算到手工资',
  },
  {
    id: 'bmi-calculator',
    name: 'BMI计算器',
    description: '计算身体质量指数，评估健康状态',
    category: 'everyday',
    icon: 'HeartIcon',
    version: '1.0.0',
    source: 'builtin',
    permissions: [],
    inputSchema: [
      { key: 'weight', label: '体重', type: 'number', placeholder: '体重(kg)', required: true },
      { key: 'height', label: '身高', type: 'number', placeholder: '身高(cm)', required: true },
    ],
    outputFormat: 'text',
    tips: '输入体重和身高即可评估健康状态',
  },
  {
    id: 'date-calculator',
    name: '日期计算器',
    description: '计算日期差、倒计时、日期推算',
    category: 'everyday',
    icon: 'CalendarIcon',
    version: '1.0.0',
    source: 'builtin',
    permissions: [],
    inputSchema: [
      {
        key: 'mode',
        label: '计算模式',
        type: 'select',
        defaultValue: 'diff',
        options: [
          { label: '计算日期差', value: 'diff' },
          { label: '日期推算', value: 'add' },
          { label: '倒计时', value: 'countdown' },
        ],
      },
      { key: 'date1', label: '日期1', type: 'text', placeholder: '日期1 (YYYY-MM-DD)', required: true },
      { key: 'date2', label: '日期2/天数', type: 'text', placeholder: '日期2/天数 (YYYY-MM-DD 或数字)', defaultValue: '' },
    ],
    outputFormat: 'text',
    tips: '支持日期差计算、日期推算和倒计时三种模式',
  },
  {
    id: 'random-decision',
    name: '随机决策器',
    description: '帮助选择困难症做决定，支持自定义选项',
    category: 'everyday',
    icon: 'DicesIcon',
    version: '1.0.0',
    source: 'builtin',
    permissions: [],
    inputSchema: [
      { key: 'options', label: '选项列表', type: 'textarea', placeholder: '每行一个选项...', required: true },
      { key: 'count', label: '选择数量', type: 'number', placeholder: '选择几个结果', defaultValue: 1 },
    ],
    outputFormat: 'text',
    tips: '每行输入一个选项，帮你快速做决定',
  },
  {
    id: 'lucky-draw',
    name: '抽奖抽签',
    description: '从名单中随机抽取，适合团建抽奖分组',
    category: 'everyday',
    icon: 'GiftIcon',
    version: '1.0.0',
    source: 'builtin',
    permissions: [],
    inputSchema: [
      { key: 'names', label: '名单', type: 'textarea', placeholder: '每行一个名字...', required: true },
      { key: 'count', label: '抽取人数', type: 'number', placeholder: '抽取人数', defaultValue: 1 },
      { key: 'allowRepeat', label: '允许重复', type: 'checkbox', defaultValue: false },
    ],
    outputFormat: 'text',
    tips: '适合团建抽奖分组，支持设置是否允许重复中奖',
  },
  {
    id: 'pomodoro-timer',
    name: '番茄钟',
    description: '专注工作计时器，支持自定义时长',
    category: 'everyday',
    icon: 'TimerIcon',
    version: '1.0.0',
    source: 'builtin',
    permissions: [],
    inputSchema: [
      { key: 'workMinutes', label: '工作时长', type: 'number', placeholder: '工作时长(分钟)', defaultValue: 25 },
      { key: 'breakMinutes', label: '休息时长', type: 'number', placeholder: '休息时长(分钟)', defaultValue: 5 },
      { key: 'rounds', label: '轮数', type: 'number', placeholder: '轮数', defaultValue: 4 },
    ],
    outputFormat: 'text',
    tips: '默认25分钟工作+5分钟休息，可自定义时长',
  },
  {
    id: 'timezone-converter',
    name: '时区转换',
    description: '在不同时区之间转换时间',
    category: 'everyday',
    icon: 'GlobeIcon',
    version: '1.0.0',
    source: 'builtin',
    permissions: [],
    inputSchema: [
      { key: 'datetime', label: '时间', type: 'text', placeholder: '时间 (YYYY-MM-DD HH:mm)', required: true },
      {
        key: 'fromTimezone',
        label: '源时区',
        type: 'select',
        defaultValue: 'Asia/Shanghai',
        options: [
          { label: '北京时间 (UTC+8)', value: 'Asia/Shanghai' },
          { label: '东京时间 (UTC+9)', value: 'Asia/Tokyo' },
          { label: '纽约时间 (UTC-5)', value: 'America/New_York' },
          { label: '伦敦时间 (UTC+0)', value: 'Europe/London' },
          { label: '洛杉矶时间 (UTC-8)', value: 'America/Los_Angeles' },
          { label: '悉尼时间 (UTC+11)', value: 'Australia/Sydney' },
        ],
      },
      {
        key: 'toTimezone',
        label: '目标时区',
        type: 'select',
        defaultValue: 'America/New_York',
        options: [
          { label: '北京时间 (UTC+8)', value: 'Asia/Shanghai' },
          { label: '东京时间 (UTC+9)', value: 'Asia/Tokyo' },
          { label: '纽约时间 (UTC-5)', value: 'America/New_York' },
          { label: '伦敦时间 (UTC+0)', value: 'Europe/London' },
          { label: '洛杉矶时间 (UTC-8)', value: 'America/Los_Angeles' },
          { label: '悉尼时间 (UTC+11)', value: 'Australia/Sydney' },
        ],
      },
    ],
    outputFormat: 'text',
    tips: '支持北京、东京、纽约、伦敦等6个主要时区互转',
  },
  {
    id: 'password-generator',
    name: '密码生成器',
    description: '生成安全的随机密码',
    icon: 'KeyRoundIcon',
    category: 'everyday',
    version: '1.0.0',
    source: 'builtin' as const,
    permissions: [],
    inputSchema: [
      { key: 'length', label: '密码长度', type: 'number', defaultValue: 16, placeholder: '密码长度' },
      { key: 'count', label: '生成数量', type: 'number', defaultValue: 5, placeholder: '生成数量' },
      { key: 'includeUpper', label: '包含大写字母', type: 'checkbox', defaultValue: true },
      { key: 'includeLower', label: '包含小写字母', type: 'checkbox', defaultValue: true },
      { key: 'includeNumbers', label: '包含数字', type: 'checkbox', defaultValue: true },
      { key: 'includeSymbols', label: '包含符号', type: 'checkbox', defaultValue: true },
    ],
    outputFormat: 'text',
    tips: '可自定义长度和字符类型，建议长度不低于12位',
  },
  {
    id: 'sensitive-mask',
    name: '敏感信息脱敏',
    description: '隐藏手机号、身份证号、银行卡号等敏感信息',
    icon: 'EyeOffIcon',
    category: 'everyday',
    version: '1.0.0',
    source: 'builtin' as const,
    permissions: [],
    inputSchema: [
      { key: 'text', label: '文本内容', type: 'textarea', placeholder: '输入包含敏感信息的文本...', required: true },
      { key: 'mode', label: '脱敏模式', type: 'select', options: [{ label: '手机号脱敏', value: 'phone' }, { label: '身份证脱敏', value: 'idcard' }, { label: '银行卡脱敏', value: 'bankcard' }, { label: '全部脱敏', value: 'all' }], defaultValue: 'all' },
    ],
    outputFormat: 'text',
    tips: '一键脱敏手机号、身份证号、银行卡号等敏感信息',
  },
  {
    id: 'simple-calculator',
    name: '简易计算器',
    description: '日常计算器，支持加减乘除和括号运算',
    icon: 'CalculatorIcon',
    category: 'everyday',
    version: '1.0.0',
    source: 'builtin' as const,
    permissions: [],
    inputSchema: [
      { key: 'expression', label: '计算表达式', type: 'text', placeholder: '例如: 100 + 200 * 3 / 4', required: true },
    ],
    outputFormat: 'text',
    tips: '支持加减乘除运算，点击等号计算结果',
  },
  {
    id: 'stopwatch',
    name: '秒表计时',
    description: '精确计时秒表，支持计次记录',
    icon: 'TimerIcon',
    category: 'everyday',
    version: '1.0.0',
    source: 'builtin' as const,
    permissions: [],
    inputSchema: [
      { key: 'action', label: '操作', type: 'select', options: [{ label: '开始计时', value: 'start' }, { label: '计次', value: 'lap' }, { label: '停止', value: 'stop' }], defaultValue: 'start' },
      { key: 'laps', label: '已有计次(逗号分隔毫秒)', type: 'text', placeholder: '留空开始新计时', defaultValue: '' },
    ],
    outputFormat: 'text',
    tips: '精确到毫秒的计时器，支持计次记录',
  },
  {
    id: 'countdown',
    name: '倒计时',
    description: '设置倒计时，计算剩余时间',
    icon: 'HourglassIcon',
    category: 'everyday',
    version: '1.0.0',
    source: 'builtin' as const,
    permissions: [],
    inputSchema: [
      { key: 'targetDate', label: '目标日期', type: 'text', placeholder: 'YYYY-MM-DD', required: true },
      { key: 'targetTime', label: '目标时间', type: 'text', placeholder: 'HH:mm', defaultValue: '00:00' },
      { key: 'eventName', label: '事件名称', type: 'text', placeholder: '例如: 项目截止日', defaultValue: '' },
    ],
    outputFormat: 'text',
    tips: '设置目标日期和事件名称，实时显示剩余时间',
  },
  {
    id: 'exchange-rate',
    name: '汇率换算',
    description: '查询实时汇率，支持主流货币互相换算',
    category: 'everyday',
    icon: 'ArrowLeftRightIcon',
    version: '1.0.0',
    source: 'builtin' as const,
    permissions: [],
    inputSchema: [
      { key: 'amount', label: '金额', type: 'number', required: true, defaultValue: 100 },
      {
        key: 'from',
        label: '源货币',
        type: 'select',
        required: true,
        defaultValue: 'USD',
        options: [
          { label: 'USD', value: 'USD' },
          { label: 'CNY', value: 'CNY' },
          { label: 'EUR', value: 'EUR' },
          { label: 'GBP', value: 'GBP' },
          { label: 'JPY', value: 'JPY' },
          { label: 'KRW', value: 'KRW' },
          { label: 'HKD', value: 'HKD' },
          { label: 'TWD', value: 'TWD' },
          { label: 'AUD', value: 'AUD' },
          { label: 'CAD', value: 'CAD' },
          { label: 'SGD', value: 'SGD' },
          { label: 'THB', value: 'THB' },
        ],
      },
      {
        key: 'to',
        label: '目标货币',
        type: 'select',
        required: true,
        defaultValue: 'CNY',
        options: [
          { label: 'USD', value: 'USD' },
          { label: 'CNY', value: 'CNY' },
          { label: 'EUR', value: 'EUR' },
          { label: 'GBP', value: 'GBP' },
          { label: 'JPY', value: 'JPY' },
          { label: 'KRW', value: 'KRW' },
          { label: 'HKD', value: 'HKD' },
          { label: 'TWD', value: 'TWD' },
          { label: 'AUD', value: 'AUD' },
          { label: 'CAD', value: 'CAD' },
          { label: 'SGD', value: 'SGD' },
          { label: 'THB', value: 'THB' },
        ],
      },
    ],
    outputFormat: 'text',
  },
  
  {
    id: 'id-card-parser',
    name: '身份证解析',
    description: '解析中国身份证号，提取地区、生日、性别信息',
    category: 'everyday',
    icon: 'IdCardIcon',
    version: '1.0.0',
    source: 'builtin' as const,
    permissions: [],
    inputSchema: [
      { key: 'idNumber', label: '身份证号', type: 'text', placeholder: '请输入18位身份证号...', required: true },
    ],
    outputFormat: 'text',
    tips: '输入18位身份证号，自动解析地区、生日、性别并校验',
  },
  
  {
    id: 'number-to-chinese',
    name: '数字转中文',
    description: '将阿拉伯数字转换为中文大写或小写',
    category: 'everyday',
    icon: 'TypeIcon',
    version: '1.0.0',
    source: 'builtin' as const,
    permissions: [],
    inputSchema: [
      { key: 'num', label: '数字', type: 'text', placeholder: '输入数字...', required: true },
      {
        key: 'mode',
        label: '格式',
        type: 'select',
        defaultValue: 'lower',
        options: [
          { label: '小写数字', value: 'lower' },
          { label: '大写金额', value: 'upper' },
        ],
      },
    ],
    outputFormat: 'text',
    tips: '支持整数和小数，大写模式可用于发票金额',
  },
  
  {
    id: 'fraction-calculator',
    name: '分数计算器',
    description: '分数加减乘除和约分，自动化简到最简形式',
    category: 'everyday',
    icon: 'DivideIcon',
    version: '1.0.0',
    source: 'builtin' as const,
    permissions: [],
    inputSchema: [
      { key: 'fraction1', label: '分数1', type: 'text', placeholder: '如 3/4', required: true },
      { key: 'fraction2', label: '分数2', type: 'text', placeholder: '如 1/2' },
      {
        key: 'op',
        label: '运算',
        type: 'select',
        defaultValue: 'add',
        options: [
          { label: '加法 (a+b)', value: 'add' },
          { label: '减法 (a-b)', value: 'subtract' },
          { label: '乘法 (a×b)', value: 'multiply' },
          { label: '除法 (a÷b)', value: 'divide' },
          { label: '约分', value: 'simplify' },
        ],
      },
    ],
    outputFormat: 'text',
    tips: '分数会自动约分到最简形式，同时显示小数结果',
  },
  {
    id: 'pet-age-calc',
    name: '宠物年龄换算',
    description: '将狗狗或猫咪的年龄换算为人类年龄',
    category: 'everyday',
    icon: 'DogIcon',
    version: '1.0.0',
    source: 'builtin' as const,
    permissions: [],
    inputSchema: [
      {
        key: 'petType',
        label: '宠物类型',
        type: 'select',
        defaultValue: 'dog',
        options: [
          { label: '狗狗', value: 'dog' },
          { label: '猫咪', value: 'cat' },
        ],
      },
      { key: 'petAge', label: '宠物年龄(岁)', type: 'number', placeholder: '输入年龄...', required: true, defaultValue: 1 },
    ],
    outputFormat: 'text',
    tips: '前两年成长快（第一年≈15岁，第二年≈9岁），之后逐年放缓',
  },
  {
    id: 'discount-calc',
    name: '折扣计算器',
    description: '计算折扣后价格，支持折扣、百分比和满减',
    category: 'everyday',
    icon: 'PercentIcon',
    version: '1.0.0',
    source: 'builtin' as const,
    permissions: [],
    inputSchema: [
      { key: 'price', label: '原价', type: 'number', placeholder: '输入原价...', required: true, defaultValue: 100 },
      { key: 'discount', label: '折扣/优惠', type: 'number', placeholder: '如8折输入8，85%输入85', required: true, defaultValue: 8 },
    ],
    outputFormat: 'text',
    tips: '输入1-10视为折扣，10-100视为百分比，大于100视为优惠金额',
  },
  {
    id: 'weighted-score-calc',
    name: '加权得分计算器',
    description: '根据分数和权重计算加权平均分和等级',
    category: 'everyday',
    icon: 'CalculatorIcon',
    version: '1.0.0',
    source: 'builtin' as const,
    permissions: [],
    inputSchema: [
      { key: 'scores', label: '分数和权重', type: 'textarea', placeholder: '每行格式：分数,权重\n如：85,3\n90,2\n78,5', required: true },
    ],
    outputFormat: 'text',
    tips: '每行输入一个科目的分数和权重，用逗号或空格分隔',
  },
  {
    id: 'clothing-size-converter',
    name: '服装尺码对照',
    description: '查询中国、美国、欧洲、日本服装鞋码对照表',
    category: 'everyday',
    icon: 'ShirtIcon',
    version: '1.0.0',
    source: 'builtin' as const,
    permissions: [],
    inputSchema: [],
    outputFormat: '',
    tips: '各品牌尺码存在差异，建议以具体品牌的官方尺码表为准',
  },
  {
    id: 'period-tracker-calc',
    name: '经期推算',
    description: '推算下个经期、排卵期和当前所处阶段',
    category: 'everyday',
    icon: 'CalendarHeartIcon',
    version: '1.0.0',
    source: 'builtin' as const,
    permissions: [],
    inputSchema: [
      { key: 'lastDate', label: '上次经期开始日期', type: 'text', placeholder: 'YYYY-MM-DD', required: true },
      { key: 'cycleDays', label: '月经周期(天)', type: 'number', placeholder: '默认28天', defaultValue: 28 },
      { key: 'periodDays', label: '经期持续(天)', type: 'number', placeholder: '默认5天', defaultValue: 5 },
    ],
    outputFormat: 'text',
    tips: '结果基于设定周期和经期天数估算，个体差异较大仅供参考',
  },
  {
    id: 'social-insurance-calc',
    name: '五险一金计算器',
    description: '计算五险一金扣除和到手工资',
    category: 'finance',
    icon: 'BanknoteIcon',
    version: '1.0.0',
    source: 'builtin' as const,
    permissions: [],
    inputSchema: [
      { key: 'salary', label: '税前工资', type: 'number', placeholder: '税前工资(元)', required: true, defaultValue: 10000 },
      { key: 'city', label: '城市', type: 'text', placeholder: '北京/上海/广州...', defaultValue: '北京' },
    ],
    outputFormat: 'text',
    tips: '按缴费基数上下限估算，实际以当地政策为准',
  },
  {
    id: 'savings-interest-calc',
    name: '存款利息计算器',
    description: '计算银行存款利息和到期本息',
    category: 'finance',
    icon: 'PercentIcon',
    version: '1.0.0',
    source: 'builtin' as const,
    permissions: [],
    inputSchema: [
      { key: 'principal', label: '本金', type: 'number', placeholder: '本金(元)', required: true, defaultValue: 10000 },
      { key: 'rate', label: '年利率', type: 'number', placeholder: '年利率(%)', required: true, defaultValue: 2 },
      { key: 'years', label: '存款年限', type: 'number', placeholder: '存款年限', required: true, defaultValue: 3 },
      {
        key: 'type',
        label: '存款类型',
        type: 'select',
        defaultValue: 'current',
        options: [
          { label: '活期', value: 'current' },
          { label: '定期复利', value: 'fixed' },
        ],
      },
    ],
    outputFormat: 'text',
    tips: '支持活期和定期复利两种计息方式',
  },
  {
    id: 'early-repayment-calc',
    name: '提前还款计算器',
    description: '计算提前还贷省下的利息和月供变化',
    category: 'finance',
    icon: 'CreditCardIcon',
    version: '1.0.0',
    source: 'builtin' as const,
    permissions: [],
    inputSchema: [
      { key: 'remaining', label: '剩余贷款', type: 'number', placeholder: '剩余贷款(元)', required: true, defaultValue: 500000 },
      { key: 'rate', label: '年利率', type: 'number', placeholder: '年利率(%)', required: true, defaultValue: 3.5 },
      { key: 'remainYears', label: '剩余年限', type: 'number', placeholder: '剩余年限', required: true, defaultValue: 20 },
      { key: 'prepay', label: '提前还款金额', type: 'number', placeholder: '提前还款金额(元)', required: true, defaultValue: 100000 },
    ],
    outputFormat: 'text',
    tips: '等额本息简化计算，实际以银行核算为准',
  },
  {
    id: 'year-end-bonus-tax-calc',
    name: '年终奖个税计算器',
    description: '计算年终奖单独计税的税额和到手金额',
    category: 'finance',
    icon: 'GiftIcon',
    version: '1.0.0',
    source: 'builtin' as const,
    permissions: [],
    inputSchema: [
      { key: 'bonus', label: '年终奖金额', type: 'number', placeholder: '年终奖金额(元)', required: true, defaultValue: 50000 },
    ],
    outputFormat: 'text',
    tips: '按全年一次性奖金单独计税方式计算',
  },
  {
    id: 'investment-return-calc',
    name: '投资收益计算器',
    description: '计算定期定投的投资收益和到期总值',
    category: 'finance',
    icon: 'TrendingUpIcon',
    version: '1.0.0',
    source: 'builtin' as const,
    permissions: [],
    inputSchema: [
      { key: 'principal', label: '初始本金', type: 'number', placeholder: '初始本金(元)', required: true, defaultValue: 10000 },
      { key: 'monthly', label: '每月定投', type: 'number', placeholder: '每月定投(元)', required: true, defaultValue: 2000 },
      { key: 'rate', label: '年化收益率', type: 'number', placeholder: '年化收益率(%)', required: true, defaultValue: 4 },
      { key: 'years', label: '投资年限', type: 'number', placeholder: '投资年限', required: true, defaultValue: 5 },
    ],
    outputFormat: 'text',
    tips: '理论复利计算，实际收益受市场波动影响',
  },
  {
    id: 'car-tax-calc',
    name: '购车费用计算器',
    description: '计算买车落地总价，含购置税和保险',
    category: 'finance',
    icon: 'CarTaxiFrontIcon',
    version: '1.0.0',
    source: 'builtin' as const,
    permissions: [],
    inputSchema: [
      { key: 'price', label: '裸车价', type: 'number', placeholder: '裸车价(元)', required: true, defaultValue: 150000 },
      { key: 'displacement', label: '排量', type: 'number', placeholder: '排量(L)', defaultValue: 1.6 },
    ],
    outputFormat: 'text',
    tips: '保险为估算值，新能源车免征购置税',
  },
  {
    id: 'calorie-calc',
    name: '热量查询与计算',
    description: '查询食物热量和运动消耗，管理日常能量摄入',
    category: 'health',
    icon: 'UtensilsCrossedIcon',
    version: '1.0.0',
    source: 'builtin' as const,
    permissions: [],
    inputSchema: [
      {
        key: 'mode',
        label: '模式',
        type: 'select',
        defaultValue: 'food',
        options: [
          { label: '食物热量', value: 'food' },
          { label: '运动消耗', value: 'sport' },
        ],
      },
      { key: 'foodName', label: '食物名称', type: 'text', placeholder: '米饭/鸡蛋/苹果...', defaultValue: '' },
      { key: 'foodWeight', label: '食物重量(g)', type: 'number', placeholder: '食物重量(克)', defaultValue: 100 },
      { key: 'sportName', label: '运动名称', type: 'text', placeholder: '跑步/游泳/跳绳...', defaultValue: '' },
      { key: 'sportMin', label: '运动时长', type: 'number', placeholder: '运动时长(分钟)', defaultValue: 30 },
      { key: 'weight', label: '体重(运动模式)', type: 'number', placeholder: '体重(kg)', defaultValue: 65 },
    ],
    outputFormat: 'text',
    tips: '内置常见食物和运动热量数据库',
  },
  {
    id: 'due-date-calc',
    name: '预产期计算器',
    description: '根据末次月经估算预产期和当前孕周',
    category: 'health',
    icon: 'BabyIcon',
    version: '1.0.0',
    source: 'builtin' as const,
    permissions: [],
    inputSchema: [
      { key: 'lmp', label: '末次月经日期', type: 'text', placeholder: 'YYYY-MM-DD', required: true },
    ],
    outputFormat: 'text',
    tips: 'Naegele公式估算，实际可能偏离±2周',
  },
  {
    id: 'body-fat-calc',
    name: '体脂率计算器',
    description: '测量体脂率，评估体脂等级和健康状态',
    category: 'health',
    icon: 'ActivityIcon',
    version: '1.0.0',
    source: 'builtin' as const,
    permissions: [],
    inputSchema: [
      { key: 'weight', label: '体重', type: 'number', placeholder: '体重(kg)', required: true },
      { key: 'waist', label: '腰围', type: 'number', placeholder: '腰围(cm)', required: true },
      { key: 'neck', label: '颈围', type: 'number', placeholder: '颈围(cm)', defaultValue: 38 },
      { key: 'height', label: '身高', type: 'number', placeholder: '身高(cm)', defaultValue: 170 },
      {
        key: 'gender',
        label: '性别',
        type: 'select',
        defaultValue: 'male',
        options: [
          { label: '男', value: 'male' },
          { label: '女', value: 'female' },
        ],
      },
      { key: 'hip', label: '臀围(女性)', type: 'number', placeholder: '臀围(cm)', defaultValue: 95 },
    ],
    outputFormat: 'text',
    tips: '美国海军方法估算，误差约±3%',
  },
  {
    id: 'bmr-calc',
    name: '基础代谢计算器',
    description: '计算BMR和TDEE，制定减脂增肌摄入计划',
    category: 'health',
    icon: 'FlameIcon',
    version: '1.0.0',
    source: 'builtin' as const,
    permissions: [],
    inputSchema: [
      { key: 'weight', label: '体重', type: 'number', placeholder: '体重(kg)', required: true, defaultValue: 65 },
      { key: 'height', label: '身高', type: 'number', placeholder: '身高(cm)', required: true, defaultValue: 170 },
      { key: 'age', label: '年龄', type: 'number', placeholder: '年龄', required: true, defaultValue: 25 },
      {
        key: 'gender',
        label: '性别',
        type: 'select',
        defaultValue: 'male',
        options: [
          { label: '男', value: 'male' },
          { label: '女', value: 'female' },
        ],
      },
      {
        key: 'activity',
        label: '活动水平',
        type: 'select',
        defaultValue: '1.55',
        options: [
          { label: '久坐不动 (1.2)', value: '1.2' },
          { label: '轻度活动 (1.375)', value: '1.375' },
          { label: '中度活动 (1.55)', value: '1.55' },
          { label: '活跃 (1.725)', value: '1.725' },
          { label: '重度活动 (1.9)', value: '1.9' },
        ],
      },
    ],
    outputFormat: 'text',
    tips: 'Mifflin-St Jeor公式，含减脂15%增肌15%建议',
  },
  {
    id: 'heart-rate-zone-calc',
    name: '心率区间计算器',
    description: '根据年龄和安静心率计算运动心率区间',
    category: 'health',
    icon: 'HeartPulseIcon',
    version: '1.0.0',
    source: 'builtin' as const,
    permissions: [],
    inputSchema: [
      { key: 'age', label: '年龄', type: 'number', placeholder: '年龄', required: true, defaultValue: 30 },
      { key: 'restHR', label: '安静心率', type: 'number', placeholder: '安静心率(次/分)', defaultValue: 70 },
    ],
    outputFormat: 'text',
    tips: 'Karvonen储备心率法计算五大运动区间',
  },
  {
    id: 'working-days-calc',
    name: '工作日计算器',
    description: '计算一段日期内的工作日天数',
    category: 'everyday',
    icon: 'CalendarDaysIcon',
    version: '1.0.0',
    source: 'builtin' as const,
    permissions: [],
    inputSchema: [
      { key: 'start', label: '开始日期', type: 'text', placeholder: 'YYYY-MM-DD', required: true },
      { key: 'days', label: '天数', type: 'number', placeholder: '天数', defaultValue: 30 },
    ],
    outputFormat: 'text',
    tips: '自动排除周末和2026年已知节假日',
  },
  {
    id: 'lunar-calendar-query',
    name: '农历查询',
    description: '查询公历日期对应的农历生肖干支信息',
    category: 'everyday',
    icon: 'MoonIcon',
    version: '1.0.0',
    source: 'builtin' as const,
    permissions: [],
    inputSchema: [
      { key: 'date', label: '日期', type: 'text', placeholder: 'YYYY-MM-DD，留空查询今天', defaultValue: '' },
    ],
    outputFormat: 'text',
    tips: '简化农历估算，精确查询请用专业黄历工具',
  },
  {
    id: 'zodiac-query',
    name: '生肖星座查询',
    description: '根据出生日期查询生肖和星座',
    category: 'everyday',
    icon: 'StarIcon',
    version: '1.0.0',
    source: 'builtin' as const,
    permissions: [],
    inputSchema: [
      { key: 'birth', label: '出生日期', type: 'text', placeholder: 'YYYY-MM-DD', required: true },
    ],
    outputFormat: 'text',
    tips: '一键查询生肖和星座',
  },
  {
    id: 'anniversary-tracker',
    name: '纪念日追踪',
    description: '管理重要纪念日，查看剩余天数',
    category: 'everyday',
    icon: 'HeartIcon',
    version: '1.0.0',
    source: 'builtin' as const,
    permissions: [],
    inputSchema: [
      { key: 'dates', label: '纪念日', type: 'textarea', placeholder: '每行一个：名称,日期\n例如：生日,2010-01-01', required: true },
    ],
    outputFormat: 'text',
    tips: '每行一个纪念日，格式：名称,日期',
  },
];
