import type { ToolRecord } from '@/types';

export const lifeTools: ToolRecord[] = [
  {
    id: 'qrcode-generator',
    name: '二维码生成',
    description: '将文本或链接生成二维码图片',
    category: 'everyday',
    icon: 'QrCodeIcon',
    version: '1.0.0',
    source: 'builtin',
    permissions: [],
    inputSchema: [
      { key: 'content', label: '内容', type: 'text', placeholder: '输入文本或链接...', required: true },
      {
        key: 'size',
        label: '尺寸',
        type: 'select',
        defaultValue: '256',
        options: [
          { label: '128x128', value: '128' },
          { label: '256x256', value: '256' },
          { label: '512x512', value: '512' },
        ],
      },
      { key: 'color', label: '前景色', type: 'color', defaultValue: '#000000' },
    ],
    outputFormat: 'image',
  },
  {
    id: 'unit-converter',
    name: '单位转换',
    description: '在长度、重量、温度等单位之间转换',
    category: 'everyday',
    icon: 'RulerIcon',
    version: '1.0.0',
    source: 'builtin',
    permissions: [],
    inputSchema: [
      { key: 'value', label: '数值', type: 'number', placeholder: '输入数值...', required: true },
      {
        key: 'category',
        label: '类别',
        type: 'select',
        defaultValue: 'length',
        options: [
          { label: '长度', value: 'length' },
          { label: '重量', value: 'weight' },
          { label: '温度', value: 'temperature' },
        ],
      },
      {
        key: 'fromUnit',
        label: '源单位',
        type: 'select',
        defaultValue: 'm',
        options: [
          { label: '米 (m)', value: 'm' },
          { label: '千米 (km)', value: 'km' },
          { label: '厘米 (cm)', value: 'cm' },
          { label: '英寸 (in)', value: 'in' },
          { label: '英尺 (ft)', value: 'ft' },
          { label: '英里 (mi)', value: 'mi' },
          { label: '千克 (kg)', value: 'kg' },
          { label: '克 (g)', value: 'g' },
          { label: '磅 (lb)', value: 'lb' },
          { label: '盎司 (oz)', value: 'oz' },
          { label: '摄氏度 (°C)', value: 'c' },
          { label: '华氏度 (°F)', value: 'f' },
          { label: '开尔文 (K)', value: 'k' },
        ],
      },
      {
        key: 'toUnit',
        label: '目标单位',
        type: 'select',
        defaultValue: 'km',
        options: [
          { label: '米 (m)', value: 'm' },
          { label: '千米 (km)', value: 'km' },
          { label: '厘米 (cm)', value: 'cm' },
          { label: '英寸 (in)', value: 'in' },
          { label: '英尺 (ft)', value: 'ft' },
          { label: '英里 (mi)', value: 'mi' },
          { label: '千克 (kg)', value: 'kg' },
          { label: '克 (g)', value: 'g' },
          { label: '磅 (lb)', value: 'lb' },
          { label: '盎司 (oz)', value: 'oz' },
          { label: '摄氏度 (°C)', value: 'c' },
          { label: '华氏度 (°F)', value: 'f' },
          { label: '开尔文 (K)', value: 'k' },
        ],
      },
    ],
    outputFormat: 'text',
  },
  {
    id: 'mortgage-calculator',
    name: '房贷计算器',
    description: '计算房贷月供、总利息和还款计划',
    category: 'everyday',
    icon: 'HomeIcon',
    version: '1.0.0',
    source: 'builtin',
    permissions: [],
    inputSchema: [
      { key: 'principal', label: '贷款金额', type: 'number', placeholder: '贷款金额(万元)', required: true, defaultValue: 100 },
      { key: 'rate', label: '年利率', type: 'number', placeholder: '年利率(%)', required: true, defaultValue: 3.5 },
      { key: 'years', label: '贷款年限', type: 'number', placeholder: '贷款年限', required: true, defaultValue: 30 },
      {
        key: 'method',
        label: '还款方式',
        type: 'select',
        defaultValue: 'equal-payment',
        options: [
          { label: '等额本息', value: 'equal-payment' },
          { label: '等额本金', value: 'equal-principal' },
        ],
      },
    ],
    outputFormat: 'text',
  },
  {
    id: 'tax-calculator',
    name: '个税计算器',
    description: '计算个人所得税和到手工资',
    category: 'everyday',
    icon: 'ReceiptIcon',
    version: '1.0.0',
    source: 'builtin',
    permissions: [],
    inputSchema: [
      { key: 'salary', label: '税前月薪', type: 'number', placeholder: '税前月薪(元)', required: true, defaultValue: 15000 },
      { key: 'socialInsurance', label: '五险一金', type: 'number', placeholder: '五险一金(元)', defaultValue: 2000 },
      { key: 'threshold', label: '起征点', type: 'number', placeholder: '起征点(元)', defaultValue: 5000 },
      { key: 'deductions', label: '专项附加扣除', type: 'number', placeholder: '专项附加扣除(元)', defaultValue: 0 },
    ],
    outputFormat: 'text',
  },
  {
    id: 'bmi-calculator',
    name: 'BMI计算器',
    description: '计算身体质量指数，评估健康状态',
    category: 'everyday',
    icon: 'HeartIcon',
    version: '1.0.0',
    source: 'builtin',
    permissions: [],
    inputSchema: [
      { key: 'weight', label: '体重', type: 'number', placeholder: '体重(kg)', required: true },
      { key: 'height', label: '身高', type: 'number', placeholder: '身高(cm)', required: true },
    ],
    outputFormat: 'text',
  },
  {
    id: 'date-calculator',
    name: '日期计算器',
    description: '计算日期差、倒计时、日期推算',
    category: 'everyday',
    icon: 'CalendarIcon',
    version: '1.0.0',
    source: 'builtin',
    permissions: [],
    inputSchema: [
      {
        key: 'mode',
        label: '计算模式',
        type: 'select',
        defaultValue: 'diff',
        options: [
          { label: '计算日期差', value: 'diff' },
          { label: '日期推算', value: 'add' },
          { label: '倒计时', value: 'countdown' },
        ],
      },
      { key: 'date1', label: '日期1', type: 'text', placeholder: '日期1 (YYYY-MM-DD)', required: true },
      { key: 'date2', label: '日期2/天数', type: 'text', placeholder: '日期2/天数 (YYYY-MM-DD 或数字)', defaultValue: '' },
    ],
    outputFormat: 'text',
  },
  {
    id: 'random-decision',
    name: '随机决策器',
    description: '帮助选择困难症做决定，支持自定义选项',
    category: 'everyday',
    icon: 'DicesIcon',
    version: '1.0.0',
    source: 'builtin',
    permissions: [],
    inputSchema: [
      { key: 'options', label: '选项列表', type: 'textarea', placeholder: '每行一个选项...', required: true },
      { key: 'count', label: '选择数量', type: 'number', placeholder: '选择几个结果', defaultValue: 1 },
    ],
    outputFormat: 'text',
  },
  {
    id: 'lucky-draw',
    name: '抽奖抽签',
    description: '从名单中随机抽取，适合团建抽奖分组',
    category: 'everyday',
    icon: 'GiftIcon',
    version: '1.0.0',
    source: 'builtin',
    permissions: [],
    inputSchema: [
      { key: 'names', label: '名单', type: 'textarea', placeholder: '每行一个名字...', required: true },
      { key: 'count', label: '抽取人数', type: 'number', placeholder: '抽取人数', defaultValue: 1 },
      { key: 'allowRepeat', label: '允许重复', type: 'checkbox', defaultValue: false },
    ],
    outputFormat: 'text',
  },
  {
    id: 'pomodoro-timer',
    name: '番茄钟',
    description: '专注工作计时器，支持自定义时长',
    category: 'everyday',
    icon: 'TimerIcon',
    version: '1.0.0',
    source: 'builtin',
    permissions: [],
    inputSchema: [
      { key: 'workMinutes', label: '工作时长', type: 'number', placeholder: '工作时长(分钟)', defaultValue: 25 },
      { key: 'breakMinutes', label: '休息时长', type: 'number', placeholder: '休息时长(分钟)', defaultValue: 5 },
      { key: 'rounds', label: '轮数', type: 'number', placeholder: '轮数', defaultValue: 4 },
    ],
    outputFormat: 'text',
  },
  {
    id: 'timezone-converter',
    name: '时区转换',
    description: '在不同时区之间转换时间',
    category: 'everyday',
    icon: 'GlobeIcon',
    version: '1.0.0',
    source: 'builtin',
    permissions: [],
    inputSchema: [
      { key: 'datetime', label: '时间', type: 'text', placeholder: '时间 (YYYY-MM-DD HH:mm)', required: true },
      {
        key: 'fromTimezone',
        label: '源时区',
        type: 'select',
        defaultValue: 'Asia/Shanghai',
        options: [
          { label: '北京时间 (UTC+8)', value: 'Asia/Shanghai' },
          { label: '东京时间 (UTC+9)', value: 'Asia/Tokyo' },
          { label: '纽约时间 (UTC-5)', value: 'America/New_York' },
          { label: '伦敦时间 (UTC+0)', value: 'Europe/London' },
          { label: '洛杉矶时间 (UTC-8)', value: 'America/Los_Angeles' },
          { label: '悉尼时间 (UTC+11)', value: 'Australia/Sydney' },
        ],
      },
      {
        key: 'toTimezone',
        label: '目标时区',
        type: 'select',
        defaultValue: 'America/New_York',
        options: [
          { label: '北京时间 (UTC+8)', value: 'Asia/Shanghai' },
          { label: '东京时间 (UTC+9)', value: 'Asia/Tokyo' },
          { label: '纽约时间 (UTC-5)', value: 'America/New_York' },
          { label: '伦敦时间 (UTC+0)', value: 'Europe/London' },
          { label: '洛杉矶时间 (UTC-8)', value: 'America/Los_Angeles' },
          { label: '悉尼时间 (UTC+11)', value: 'Australia/Sydney' },
        ],
      },
    ],
    outputFormat: 'text',
  },
  {
    id: 'password-generator',
    name: '密码生成器',
    description: '生成安全的随机密码',
    icon: 'KeyRoundIcon',
    category: 'everyday',
    version: '1.0.0',
    source: 'builtin' as const,
    permissions: [],
    inputSchema: [
      { key: 'length', label: '密码长度', type: 'number', defaultValue: 16, placeholder: '密码长度' },
      { key: 'count', label: '生成数量', type: 'number', defaultValue: 5, placeholder: '生成数量' },
      { key: 'includeUpper', label: '包含大写字母', type: 'checkbox', defaultValue: true },
      { key: 'includeLower', label: '包含小写字母', type: 'checkbox', defaultValue: true },
      { key: 'includeNumbers', label: '包含数字', type: 'checkbox', defaultValue: true },
      { key: 'includeSymbols', label: '包含符号', type: 'checkbox', defaultValue: true },
    ],
    outputFormat: 'text',
  },
  {
    id: 'sensitive-mask',
    name: '敏感信息脱敏',
    description: '隐藏手机号、身份证号、银行卡号等敏感信息',
    icon: 'EyeOffIcon',
    category: 'everyday',
    version: '1.0.0',
    source: 'builtin' as const,
    permissions: [],
    inputSchema: [
      { key: 'text', label: '文本内容', type: 'textarea', placeholder: '输入包含敏感信息的文本...', required: true },
      { key: 'mode', label: '脱敏模式', type: 'select', options: [{ label: '手机号脱敏', value: 'phone' }, { label: '身份证脱敏', value: 'idcard' }, { label: '银行卡脱敏', value: 'bankcard' }, { label: '全部脱敏', value: 'all' }], defaultValue: 'all' },
    ],
    outputFormat: 'text',
  },
  {
    id: 'simple-calculator',
    name: '简易计算器',
    description: '日常计算器，支持加减乘除和括号运算',
    icon: 'CalculatorIcon',
    category: 'everyday',
    version: '1.0.0',
    source: 'builtin' as const,
    permissions: [],
    inputSchema: [
      { key: 'expression', label: '计算表达式', type: 'text', placeholder: '例如: 100 + 200 * 3 / 4', required: true },
    ],
    outputFormat: 'text',
  },
  {
    id: 'stopwatch',
    name: '秒表计时',
    description: '精确计时秒表，支持计次记录',
    icon: 'TimerIcon',
    category: 'everyday',
    version: '1.0.0',
    source: 'builtin' as const,
    permissions: [],
    inputSchema: [
      { key: 'action', label: '操作', type: 'select', options: [{ label: '开始计时', value: 'start' }, { label: '计次', value: 'lap' }, { label: '停止', value: 'stop' }], defaultValue: 'start' },
      { key: 'laps', label: '已有计次(逗号分隔毫秒)', type: 'text', placeholder: '留空开始新计时', defaultValue: '' },
    ],
    outputFormat: 'text',
  },
  {
    id: 'countdown',
    name: '倒计时',
    description: '设置倒计时，计算剩余时间',
    icon: 'HourglassIcon',
    category: 'everyday',
    version: '1.0.0',
    source: 'builtin' as const,
    permissions: [],
    inputSchema: [
      { key: 'targetDate', label: '目标日期', type: 'text', placeholder: 'YYYY-MM-DD', required: true },
      { key: 'targetTime', label: '目标时间', type: 'text', placeholder: 'HH:mm', defaultValue: '00:00' },
      { key: 'eventName', label: '事件名称', type: 'text', placeholder: '例如: 项目截止日', defaultValue: '' },
    ],
    outputFormat: 'text',
  },
];
