import type { ToolRecord } from '@/types';

export const magicTools: ToolRecord[] = [
  {
    id: 'photo-restore',
    name: '老照片修复',
    description: '上传发黄褪色的老照片，一键去除泛黄、增强对比度、锐化修复',
    category: 'image',
    icon: 'UserIcon',
    version: '1.0.0',
    source: 'builtin',
    permissions: [],
    inputSchema: [
      { key: 'file', label: '选择老照片', type: 'file', accept: 'image/*', required: true },
    ],
    outputFormat: 'blob',
    tips: '自动去黄、增强对比度、边缘锐化，适用于泛黄褪色的旧照片',
  },
  {
    id: 'ai-bg-remove',
    name: 'AI一键抠图',
    description: '上传照片自动识别背景并移除，生成透明PNG图片',
    category: 'image',
    icon: 'EraserIcon',
    version: '1.0.0',
    source: 'builtin',
    permissions: [],
    inputSchema: [
      { key: 'file', label: '选择图片', type: 'file', accept: 'image/*', required: true },
      { key: 'threshold', label: '识别灵敏度', type: 'number', defaultValue: 30, placeholder: '10-80，越小越敏感' },
      { key: 'feather', label: '边缘羽化', type: 'number', defaultValue: 2, placeholder: '1-5，越大过渡越自然' },
    ],
    outputFormat: 'blob',
    tips: '适合背景较纯的照片，建议调整灵敏度和羽化获得最佳效果',
  },
  {
    id: 'text-to-handwriting',
    name: '文字转手写体',
    description: '输入文字生成逼真的手写笔记效果，可选横线纸、方格纸、空白纸',
    category: 'fun',
    icon: 'PenToolIcon',
    version: '1.0.0',
    source: 'builtin',
    permissions: [],
    inputSchema: [
      { key: 'text', label: '输入文字', type: 'textarea', placeholder: '输入要转换成手写体的文字...', defaultValue: '', rows: 6 },
      { key: 'paperStyle', label: '纸张样式', type: 'select', defaultValue: 'lined', options: [{ label: '横线纸', value: 'lined' }, { label: '方格纸', value: 'grid' }, { label: '空白纸', value: 'blank' }] },
    ],
    outputFormat: 'blob',
    tips: '每个字有微小的随机旋转和偏移，模仿真实手写的自然感',
  },
  {
    id: 'word-cloud',
    name: '词云生成器',
    description: '粘贴文本自动统计词频并生成精美词云图',
    category: 'fun',
    icon: 'ImagePlayIcon',
    version: '1.0.0',
    source: 'builtin',
    permissions: [],
    inputSchema: [
      { key: 'text', label: '粘贴文本', type: 'textarea', placeholder: '粘贴要生成词云的文本内容...', defaultValue: '', rows: 8 },
      { key: 'colorScheme', label: '配色方案', type: 'select', defaultValue: 'warm', options: [{ label: '暖色系', value: 'warm' }, { label: '冷色系', value: 'cool' }, { label: '紫色系', value: 'purple' }, { label: '霓虹色', value: 'neon' }] },
    ],
    outputFormat: 'blob',
    tips: '词频越高字体越大，支持中文和英文词汇自动分词',
  },
  {
    id: 'pixel-art',
    name: '像素画生成',
    description: '将照片转换为复古8-bit像素风格艺术作品',
    category: 'image',
    icon: 'RowsIcon',
    version: '1.0.0',
    source: 'builtin',
    permissions: [],
    inputSchema: [
      { key: 'file', label: '选择图片', type: 'file', accept: 'image/*', required: true },
      { key: 'pixelSize', label: '像素块大小', type: 'number', defaultValue: 8, placeholder: '4-16' },
      { key: 'colorCount', label: '颜色数量', type: 'number', defaultValue: 16, placeholder: '8-64' },
    ],
    outputFormat: 'blob',
    tips: '像素块越大越复古，颜色数量越少越像素化',
  },
  {
    id: 'photo-sketch',
    name: '照片转素描',
    description: '将照片一键转换为铅笔素描风格，支持调节强度',
    category: 'image',
    icon: 'PenToolIcon',
    version: '1.0.0',
    source: 'builtin',
    permissions: [],
    inputSchema: [
      { key: 'file', label: '选择照片', type: 'file', accept: 'image/*', required: true },
      { key: 'intensity', label: '线条强度', type: 'number', defaultValue: 1, placeholder: '0.5-2.0' },
    ],
    outputFormat: 'blob',
    tips: '使用Sobel边缘检测算法+灰度反相实现素描效果',
  },
  {
    id: 'led-marquee',
    name: '手持弹幕',
    description: '输入文字生成全屏LED滚动弹幕，保存为HTML文件打开即可使用',
    category: 'fun',
    icon: 'SmilePlusIcon',
    version: '1.0.0',
    source: 'builtin',
    permissions: [],
    inputSchema: [
      { key: 'text', label: '弹幕文字', type: 'text', placeholder: '输入显示的文字...', defaultValue: '我爱你们！', required: true },
      { key: 'speed', label: '滚动速度', type: 'select', defaultValue: 'medium', options: [{ label: '快速', value: 'fast' }, { label: '正常', value: 'medium' }, { label: '慢速', value: 'slow' }] },
      { key: 'color', label: '文字颜色', type: 'color', defaultValue: '#00ff88' },
    ],
    outputFormat: 'blob',
    tips: '下载HTML后用浏览器打开，全屏显示(F11)，适合演唱会、运动会、活动应援',
  },
  {
    id: 'lucky-wheel',
    name: '抽奖转盘',
    description: '输入参与者名单，生成可互动旋转的抽奖转盘动画',
    category: 'fun',
    icon: 'SmilePlusIcon',
    version: '1.0.0',
    source: 'builtin',
    permissions: [],
    inputSchema: [
      { key: 'names', label: '参与者名单', type: 'textarea', placeholder: '张三\n李四\n王五\n赵六\n（一行一个名字）', defaultValue: '', rows: 6, required: true },
      { key: 'title', label: '转盘标题', type: 'text', defaultValue: '抽奖转盘', placeholder: '抽奖转盘' },
    ],
    outputFormat: 'blob',
    tips: '下载HTML后用浏览器打开，点击按钮转动转盘，动画结束后显示结果',
  },
];