import type { ToolRecord } from '@/types';

export const pdfTools: ToolRecord[] = [
  {
    id: 'pdf-toolbox',
    name: 'PDF工具箱',
    description: 'PDF拆分、签名、压缩、加密、解密、权限设置、转Word，一站式PDF处理',
    category: 'image',
    icon: 'FileTextIcon',
    version: '2.0.0',
    source: 'builtin',
    permissions: [],
    inputSchema: [
      {
        key: 'mode',
        label: '选择功能',
        type: 'select',
        defaultValue: 'split',
        options: [
          { label: '✂️ PDF拆分', value: 'split' },
          { label: '✍️ PDF签名', value: 'sign' },
          { label: '📦 PDF压缩', value: 'compress' },
          { label: '🔒 PDF加密', value: 'encrypt' },
          { label: '🔓 PDF解密', value: 'decrypt' },
          { label: '🛡️ 权限设置', value: 'permissions' },
          { label: '📝 转Word/文本', value: 'to-word' },
        ],
      },
      { key: 'file', label: '选择PDF文件', type: 'file', accept: '.pdf', required: true },
      { key: 'password', label: '密码（加密/解密/权限用）', type: 'text', placeholder: '设置或输入密码', defaultValue: '' },
      { key: 'ownerPassword', label: '管理员密码（可选，加密用）', type: 'text', placeholder: '留空则与用户密码相同', defaultValue: '' },
      {
        key: 'algorithm',
        label: '加密算法（加密用）',
        type: 'select',
        defaultValue: 'AES-256',
        options: [
          { label: 'AES-256（推荐，PDF 2.0）', value: 'AES-256' },
          { label: 'RC4 128-bit（兼容旧版阅读器）', value: 'RC4' },
        ],
      },
      { key: 'allowPrint', label: '允许打印', type: 'checkbox', defaultValue: true },
      { key: 'allowCopy', label: '允许复制', type: 'checkbox', defaultValue: true },
      { key: 'allowModify', label: '允许修改', type: 'checkbox', defaultValue: false },
      { key: 'allowAnnotate', label: '允许批注', type: 'checkbox', defaultValue: true },
      { key: 'pages', label: '页码范围（拆分用）', type: 'text', placeholder: '如: 1,3-5,7 (留空取第一页)', defaultValue: '' },
      { key: 'signFile', label: '签名图片（签名用）', type: 'file', accept: 'image/png,image/jpeg' },
      { key: 'pageNum', label: '签名页码', type: 'number', defaultValue: 1, placeholder: '1' },
      { key: 'x', label: '签名X坐标', type: 'number', defaultValue: 50, placeholder: '50' },
      { key: 'y', label: '签名Y坐标', type: 'number', defaultValue: 50, placeholder: '50' },
      { key: 'scale', label: '签名缩放', type: 'number', defaultValue: 0.3, placeholder: '0.3' },
      {
        key: 'saveType',
        label: '导出格式（转Word用）',
        type: 'select',
        defaultValue: 'docx',
        options: [
          { label: 'Word (.docx)', value: 'docx' },
          { label: '纯文本 (.txt)', value: 'txt' },
        ],
      },
    ],
    outputFormat: 'blob',
    tips: '选择上方功能后，填写对应参数即可。加密使用 AES-256 标准，Adobe Acrobat 可直接打开',
  },
];