import type { ToolRecord } from '@/types';

export const pdfTools: ToolRecord[] = [
  {
    id: 'pdf-split',
    name: 'PDF拆分',
    description: '按页数或页码范围将PDF拆分为多个独立文件',
    category: 'image',
    icon: 'FileStackIcon',
    version: '1.0.0',
    source: 'builtin',
    permissions: [],
    inputSchema: [
      { key: 'file', label: '选择PDF文件', type: 'file', accept: '.pdf', required: true },
      { key: 'pages', label: '页码范围', type: 'text', placeholder: '如: 1,3-5,7 (留空取第一页)', defaultValue: '' },
    ],
    outputFormat: 'blob',
    tips: '支持逗号分隔的单页和范围: 1,3-5,7 表示第1页、第3-5页、第7页',
  },
  {
    id: 'pdf-sign',
    name: 'PDF签名',
    description: '在PDF文档中插入手写签名的图片标注',
    category: 'image',
    icon: 'PenToolIcon',
    version: '1.0.0',
    source: 'builtin',
    permissions: [],
    inputSchema: [
      { key: 'file', label: '选择PDF文件', type: 'file', accept: '.pdf', required: true },
      { key: 'signFile', label: '签名图片', type: 'file', accept: 'image/png,image/jpeg', required: true },
      { key: 'pageNum', label: '目标页码', type: 'number', defaultValue: 1, placeholder: '1' },
      { key: 'x', label: 'X坐标 (从左)', type: 'number', defaultValue: 50, placeholder: '50' },
      { key: 'y', label: 'Y坐标 (从下)', type: 'number', defaultValue: 50, placeholder: '50' },
      { key: 'scale', label: '缩放比例', type: 'number', defaultValue: 0.3, placeholder: '0.3' },
    ],
    outputFormat: 'blob',
    tips: '签名图片建议使用电子签名工具生成透明的PNG签名贴图',
  },
  {
    id: 'pdf-compress',
    name: 'PDF压缩',
    description: '减小PDF文件体积，优化对象流，便于传输和存储',
    category: 'image',
    icon: 'FileDownIcon',
    version: '1.0.0',
    source: 'builtin',
    permissions: [],
    inputSchema: [
      { key: 'file', label: '选择PDF文件', type: 'file', accept: '.pdf', required: true },
    ],
    outputFormat: 'blob',
    tips: '压缩效果取决于PDF内容，文字型PDF压缩效果好，扫描版效果有限',
  },
  {
    id: 'pdf-encrypt',
    name: 'PDF加密',
    description: '为PDF文件设置密码保护，防止未授权访问',
    category: 'image',
    icon: 'KeyRoundIcon',
    version: '1.0.0',
    source: 'builtin',
    permissions: [],
    inputSchema: [
      { key: 'file', label: '选择PDF文件', type: 'file', accept: '.pdf', required: true },
      { key: 'password', label: '设置密码', type: 'text', placeholder: '至少4位密码', required: true },
    ],
    outputFormat: 'blob',
    tips: '请妥善保管密码，丢失后文件将无法打开',
  },
  {
    id: 'pdf-decrypt',
    name: 'PDF解密',
    description: '输入密码移除PDF的加密保护',
    category: 'image',
    icon: 'EyeOffIcon',
    version: '1.0.0',
    source: 'builtin',
    permissions: [],
    inputSchema: [
      { key: 'file', label: '选择加密PDF', type: 'file', accept: '.pdf', required: true },
      { key: 'password', label: '输入密码', type: 'text', placeholder: '输入PDF密码', required: true },
    ],
    outputFormat: 'blob',
    tips: '需要知道原PDF的加密密码才能解密',
  },
  {
    id: 'pdf-permissions',
    name: 'PDF权限设置',
    description: '限制PDF的打印、复制、修改等操作权限',
    category: 'image',
    icon: 'UsersIcon',
    version: '1.0.0',
    source: 'builtin',
    permissions: [],
    inputSchema: [
      { key: 'file', label: '选择PDF文件', type: 'file', accept: '.pdf', required: true },
      { key: 'password', label: '权限密码', type: 'text', placeholder: '至少4位', required: true },
      { key: 'allowPrint', label: '允许打印', type: 'checkbox', defaultValue: true },
      { key: 'allowCopy', label: '允许复制', type: 'checkbox', defaultValue: true },
      { key: 'allowModify', label: '允许修改', type: 'checkbox', defaultValue: true },
      { key: 'allowAnnotate', label: '允许批注', type: 'checkbox', defaultValue: true },
    ],
    outputFormat: 'blob',
    tips: '取消勾选对应的操作即可限制，请妥善保管权限密码',
  },
  {
    id: 'image-table-to-excel',
    name: '图片表格转Excel',
    description: 'OCR识别图片中的表格结构并导出为Excel或CSV',
    category: 'image',
    icon: 'FileDownIcon',
    version: '1.0.0',
    source: 'builtin',
    permissions: [],
    inputSchema: [
      { key: 'file', label: '选择表格图片', type: 'file', accept: 'image/*', required: true },
      { key: 'saveType', label: '导出格式', type: 'select', defaultValue: 'xlsx', options: [{ label: 'Excel (.xlsx)', value: 'xlsx' }, { label: 'CSV (.csv)', value: 'csv' }] },
    ],
    outputFormat: 'blob',
    tips: '表格结构为自动识别，复杂的合并单元格可能无法完美还原',
  },
  {
    id: 'pdf-to-word',
    name: 'PDF转Word',
    description: '提取PDF中的文字内容并导出为Word文档(.docx)或纯文本(.txt)',
    category: 'image',
    icon: 'FileTextIcon',
    version: '1.0.0',
    source: 'builtin',
    permissions: [],
    inputSchema: [
      { key: 'file', label: '选择PDF文件', type: 'file', accept: '.pdf', required: true },
      { key: 'saveType', label: '导出格式', type: 'select', defaultValue: 'docx', options: [{ label: 'Word (.docx)', value: 'docx' }, { label: '纯文本 (.txt)', value: 'txt' }] },
    ],
    outputFormat: 'blob',
    tips: '仅提取文字内容，扫描版图片PDF无法提取，建议用OCR识别',
  },
];